.define MEM_LOW_RAM_END $2000
.define MEM_STACK_TOP MEM_LOW_RAM_END

.define MEM_SRAM_BEGIN $700000.l
.define MEM_SRAM_SIZE $2000
.define MEM_SRAM_MIRROR_BEGIN MEM_SRAM_BEGIN + MEM_SRAM_SIZE

.define MEM_LOW_HIGH_RAM_BEGIN $7e0000.l
.define MEM_LOW_HIGH_RAM_BANK MEM_LOW_HIGH_RAM_BEGIN >> 16

.define MEM_HIGH_RAM_BEGIN $7f0000.l
